### ISSUE TITLE
#1 launchTest.sh results in an error

### ISSUE THREAD

**Issue by sylvain-viole** [sylvain-viole/Postman-auto-test_GBooks-API#1]
|  |  |  |
|-|-|-|
| Id | #1 |  |
| Title |  launchTest.sh results in an error |  |
| description | When user launches ```launchTest.sh``` the terminal returns on error|  |
| Steps | - User on the local folder of the repo<br>- inputs inputs ```bash launchTest.sh```<br> Newman test launches<br> Newman test finishes<br><br>GET<br>==> ```fatal: le chemin 'newman?' ne correspond à aucun fichier```<br>EXPECTED<br>==> completion of process : git add =>  git commit => git push |  |
| Frequency | Systematic |  |
| Attachments | See below |  |
| Datas | none |  |
| Logs | NC |  |
| Device | iMac 27'' mid 2012 |  |
| OS | 10.13.6 |  |
| Software | iTerm2 Build 3.3.12 |  |
| Date | 09/04/2021 @ 18h31 |  |
| Critical estimation | HIGH |  |

![Capture d’écran 2021-04-09 à 18 32 10](https://user-images.githubusercontent.com/71819292/114212291-f23ea000-9961-11eb-9439-2c3a7e7f11e4.png)

[source code](https://github.com/sylvain-viole/Postman-auto-test_GBooks-API/blob/main/launchTest.sh)

**Comment by wmedali** [comment]
@sylvain-viole I wouldn't recommend to commit the report each time to Github, it's should be used to host source code and artifacts/test reports.
Instead you can use the discord api, using webhooks ans send the file directly to your team channel (cf. https://discord.com/developers/docs/resources/webhook#execute-webhook)
You might use [cURL ](https://fr.wikipedia.org/wiki/CURL) for http requests from command line, it's available by default in mac/linux systems.
Besides that, the issue here is that your newman run task is asynchronous, so you'll need to wait for it to complete before executing the `git commit` .. you can [wait ](https://stackoverflow.com/questions/1131484/wait-for-bash-background-jobs-in-script-to-be-finished) instead of sleep

**Comment by sylvain-viole** [comment]
Thank you @wmedali for your advices, I just updated the script.
Test report file is now sent directly to the discord server.

**Comment by sylvain-viole** [comment]
**commit 0e4f10c closes this issue**

**Comment by wmedali** [comment]
It would be cool if you add a screenshot of Discord message to your README
You can also [check this link](https://learning.postman.com/docs/running-collections/using-newman-cli/integration-with-travis/) to make distant servers execute and launch your tests and reporting also, instead of running it locally 😜 Good luck !
